columns:
  - userId: int64
  - movieId: int64
  - rating: float64
  - timestamp: int64
  - title: object
  - genres: object

numerical_columns:
  - userId
  - movieId
  - rating
  - timestamp

categorical_columns:
  - title
  - genres
